---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faux-operator
  namespace: faux-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: com.github.danpfe.eclipsecon.faux-operator
rules:
  - apiGroups:
      - "com.github.danpfe.eclipsecon"
    resources:
      - "samples"
      - "samples/status"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: com.github.danpfe.eclipsecon.faux-operator.namespace
  namespace: faux-operator
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: com.github.danpfe.eclipsecon.faux-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: com.github.danpfe.eclipsecon.faux-operator
subjects:
  - kind: ServiceAccount
    name: faux-operator
    namespace: faux-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: com.github.danpfe.eclipsecon.faux-operator.namespace
  namespace: faux-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: com.github.danpfe.eclipsecon.faux-operator.namespace
subjects:
  - kind: ServiceAccount
    name: faux-operator
    namespace: faux-operator
